# Generated by Django 6.0.6 on 2026-07-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('temperature', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('weather_condition', models.CharField(max_length=150)),
                ('search_date', models.DateField(auto_now_add=True)),
                ('search_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
