# Generated by Django 6.0.6 on 2026-07-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0002_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=1),
        ),
    ]
