# Generated by Django 6.0.6 on 2026-07-07 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapi', '0003_alter_signup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
